image: Ubuntu  # образ для сборки
stack: jdk 11
branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки
install: -java -jar./artifacts/app-mbank.jar
build_script:
  - ./gradlew build